# Generated by Django 4.2.3 on 2023-07-29 17:25

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_book_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specializations',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=32)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=32)),
        ),
    ]
